/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import java.util.Enumeration;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.core.util.CoreList;
import com.dts.project.dao.SellItemDAO;

/**
 * MyEclipse Struts Creation date: 02-21-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AuctionItemsToday extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			HttpSession session = request.getSession();
			String loginname = (String) session.getAttribute("user");
			SellItemDAO adao = new SellItemDAO();
			CoreList acorelist = adao.generalauctionItemDetails();
			int size = acorelist.size();

			if (size != 0) {
				System.out.println("This is auction item details" + request);
				request.setAttribute("ViewAuctionItems", acorelist);
				return mapping.findForward("ViewAuctionItems");
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("norecords");
	}
}