/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.core.util.CoreList;
import com.dts.project.dao.SellItemDAO;
import com.dts.project.model.ItemModel;

/**
 * MyEclipse Struts Creation date: 03-01-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/viewItemAction" name="itemmodel" scope="request"
 * @struts.action-forward name="viewItems" path="/ViewItems.jsp"
 * @struts.action-forward name="norecords" path="/Success1.jsp?status=NoRecords
 *                        Found"
 */
public class ViewItemAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		try {
			SellItemDAO adao = new SellItemDAO();
			String loginname = (String) request.getSession().getAttribute("user");
			CoreList acorelist = adao.viewItems(loginname);
			int size = acorelist.size();
			if (size != 0) {
				request.setAttribute("ViewItems", acorelist);
				return mapping.findForward("ViewItems");
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("norecords");
	}
}