/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dts.core.util.CoreList;
import com.dts.project.dao.CategoryDAO;
import com.dts.project.model.CategoryModel;

/**
 * MyEclipse Struts Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/viewCategoryAction" name="categorymodel"
 *                scope="request"
 * @struts.action-forward name="viewCategorys" path="/ViewCategorys.jsp"
 * @struts.action-forward name="norecords" path="/Success.jsp?status=No Records
 *                        Found "
 */
public class ViewCategoryAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		try {
			CategoryDAO adao = new CategoryDAO();
			CoreList acorelist = adao.viewCategorys();
			int size = acorelist.size();
			if (size != 0) {
				request.setAttribute("ViewCategorys", acorelist);
				return mapping.findForward("viewCategorys");
			}

		} catch (Exception e) {
			e.printStackTrace();
			// TODO: handle exception
		}
		return mapping.findForward("norecords");
	}
}