/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 03-01-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="biddermodel"
 */
public class BidderForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** bidderdate property */
	private String bidderdate;

	/** itemname property */
	private String itemname;

	/** bidderid property */
	private int bidderid;

	/** loginname property */
	private String loginname;

	/** bamount property */
	private int bamount;

	/** status property */
	private String status;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the bidderdate.
	 * 
	 * @return String
	 */
	public String getBidderdate() {
		return bidderdate;
	}

	/**
	 * Set the bidderdate.
	 * 
	 * @param bidderdate The bidderdate to set
	 */
	public void setBidderdate(String bidderdate) {
		this.bidderdate = bidderdate;
	}

	/**
	 * Returns the itemname.
	 * 
	 * @return String
	 */
	public String getItemname() {
		return itemname;
	}

	/**
	 * Set the itemname.
	 * 
	 * @param itemname The itemname to set
	 */
	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	/**
	 * Returns the bidderid.
	 * 
	 * @return int
	 */
	public int getBidderid() {
		return bidderid;
	}

	/**
	 * Set the bidderid.
	 * 
	 * @param bidderid The bidderid to set
	 */
	public void setBidderid(int bidderid) {
		this.bidderid = bidderid;
	}

	/**
	 * Returns the loginname.
	 * 
	 * @return String
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * Set the loginname.
	 * 
	 * @param loginname The loginname to set
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * Returns the bamount.
	 * 
	 * @return int
	 */
	public int getBamount() {
		return bamount;
	}

	/**
	 * Set the bamount.
	 * 
	 * @param bamount The bamount to set
	 */
	public void setBamount(int bamount) {
		this.bamount = bamount;
	}

	/**
	 * Returns the status.
	 * 
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Set the status.
	 * 
	 * @param status The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}