/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 02-28-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="categorymodel"
 */
public class CategoryModel extends ActionForm {
	/*
	 * Generated fields
	 */

	/** categoryabbr property */
	private String categoryabbr;

	/** categoryname property */
	private String categoryname;

	/** categorydesc property */
	private String categorydesc;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the categoryabbr.
	 * 
	 * @return String
	 */
	public String getCategoryabbr() {
		return categoryabbr;
	}

	/**
	 * Set the categoryabbr.
	 * 
	 * @param categoryabbr The categoryabbr to set
	 */
	public void setCategoryabbr(String categoryabbr) {
		this.categoryabbr = categoryabbr;
	}

	/**
	 * Returns the categoryname.
	 * 
	 * @return String
	 */
	public String getCategoryname() {
		return categoryname;
	}

	/**
	 * Set the categoryname.
	 * 
	 * @param categoryname The categoryname to set
	 */
	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	/**
	 * Returns the categorydesc.
	 * 
	 * @return String
	 */
	public String getCategorydesc() {
		return categorydesc;
	}

	/**
	 * Set the categorydesc.
	 * 
	 * @param categorydesc The categorydesc to set
	 */
	public void setCategorydesc(String categorydesc) {
		this.categorydesc = categorydesc;
	}
}