/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dts.project.model;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 03-01-2009
 * 
 * XDoclet definition:
 * 
 * @struts.form name="itemmodel"
 */
public class ItemModel extends ActionForm {
	/*
	 * Generated fields
	 */

	/** summary property */
	private String summary;

	/** startprice property */
	private int startprice;

	/** itemdesc property */
	private String itemdesc;

	/** categoryname property */
	private String categoryname;

	/** itemname property */
	private String itemname;

	/** loginname property */
	private String loginname;

	/** endingdate property */
	private String endingdate;

	/** incrprice property */
	private int incrprice;

	/** bidcount property */
	private int bidcount;

	/** startingdate property */
	private String startingdate;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the summary.
	 * 
	 * @return String
	 */
	public String getSummary() {
		return summary;
	}

	/**
	 * Set the summary.
	 * 
	 * @param summary The summary to set
	 */
	public void setSummary(String summary) {
		this.summary = summary;
	}

	/**
	 * Returns the startprice.
	 * 
	 * @return int
	 */
	public int getStartprice() {
		return startprice;
	}

	/**
	 * Set the startprice.
	 * 
	 * @param startprice The startprice to set
	 */
	public void setStartprice(int startprice) {
		this.startprice = startprice;
	}

	/**
	 * Returns the itemdesc.
	 * 
	 * @return String
	 */
	public String getItemdesc() {
		return itemdesc;
	}

	/**
	 * Set the itemdesc.
	 * 
	 * @param itemdesc The itemdesc to set
	 */
	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}

	/**
	 * Returns the categoryname.
	 * 
	 * @return String
	 */
	public String getCategoryname() {
		return categoryname;
	}

	/**
	 * Set the categoryname.
	 * 
	 * @param categoryname The categoryname to set
	 */
	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	/**
	 * Returns the itemname.
	 * 
	 * @return String
	 */
	public String getItemname() {
		return itemname;
	}

	/**
	 * Set the itemname.
	 * 
	 * @param itemname The itemname to set
	 */
	public void setItemname(String itemname) {
		this.itemname = itemname;
	}

	/**
	 * Returns the loginname.
	 * 
	 * @return String
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * Set the loginname.
	 * 
	 * @param loginname The loginname to set
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	/**
	 * Returns the endingdate.
	 * 
	 * @return String
	 */
	public String getEndingdate() {
		return endingdate;
	}

	/**
	 * Set the endingdate.
	 * 
	 * @param endingdate The endingdate to set
	 */
	public void setEndingdate(String endingdate) {
		this.endingdate = endingdate;
	}

	/**
	 * Returns the incrprice.
	 * 
	 * @return String
	 */
	public int getIncrprice() {
		return incrprice;
	}

	/**
	 * Set the incrprice.
	 * 
	 * @param incrprice The incrprice to set
	 */
	public void setIncrprice(int incrprice) {
		this.incrprice = incrprice;
	}

	/**
	 * Returns the bidcount.
	 * 
	 * @return int
	 */
	public int getBidcount() {
		return bidcount;
	}

	/**
	 * Set the bidcount.
	 * 
	 * @param bidcount The bidcount to set
	 */
	public void setBidcount(int bidcount) {
		this.bidcount = bidcount;
	}

	/**
	 * Returns the startingdate.
	 * 
	 * @return String
	 */
	public String getStartingdate() {
		return startingdate;
	}

	/**
	 * Set the startingdate.
	 * 
	 * @param startingdate The startingdate to set
	 */
	public void setStartingdate(String startingdate) {
		this.startingdate = startingdate;
	}
}